const map = {
    'annepink': 'like',
    'aaronli': 'like',
    'abcallen': 'like',
    'aellly': 'like',
    'ahua': 'like',
    'annzhao': 'like',
    'asyoulikeit': 'like',
    'caishin': 'like',
    'cherryzz': 'like',
    'cloudblade': 'like',
    'cnfund': 'like',
    'elizacheng': 'like',
    'ericet': 'like',
    'honoru': 'like',
    'jianan': 'like',
    'julian2013': 'like',
    'kevin.zhangkq': 'like',
    'liumei': 'like',
    'lnakuma': 'like',
    'minloulou': 'like',
    'mrspointm': 'like',
    'mylord1992': 'like',
    'nuagnorab': 'like',
    'pet.society': 'like',
    'shenchensucc': 'like',
    'slientstorm': 'like',
    'softmetal': 'like',
    'sunai': 'like',
    'tanlikming': 'like',
    'tiffany4ever': 'like',
    'tsomur': 'like',
    'ybeyond': 'like',
    'youandme': 'like',
    'steem-drivers':'like',
    'cn-trail':'like',
    'teamcn-shop':'like',
    'cn-union':'like',
};

export default map;
