const map = {
    ericet: 'like',
    honoru: 'like',
    softmetal: 'like',
    annepink: 'like',
    annzhao: 'like',
    cnfund: 'like',
    aellly: 'like',
    cherryzz: 'like',
    mrspointm: 'like',
    shenchensucc: 'like',
    lnakuma: 'like',
    abcallen: 'like',
    aaronli: 'like',
    nuagnorab: 'like',
    sunai: 'like',
    tsomur: 'like',
    liumei: 'like',
    cloudblade: 'like',
    caishin: 'like',
    jianan: 'like',
    'kevin.zhangkq': 'like',
};

export default map;
